# This file is auto-generated by syncinstalledapps.
INSTALLED_APPS_AUTOGEN = [
    "abst.entity",
    "abst.entity.actorcore",
    "abst.entity.actorcore.sessioncore",
    "abst.entity.actorcore.sessioncore.usercore",
    "abst.entity.actorcore.sessioncore.usercore.financecore",
    "abst.entity.actorcore.sessioncore.usercore.financecore.franchisecore",
    "abst.entity.actorcore.sessioncore.usercore.financecore.franchisecore.unroucore",
    "impl.unrou",
    "impl.unrou.course",
    "impl.unrou.salse",
    "tools.developments",
]
